import { StyleSheet } from "react-native";
const StyleView = StyleSheet.create({
    viewheader:
    {
        flex:1,
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center'
    },
    text:
    {
        color:'black',
        fontSize:20,
        justifyContent:'flex-start',
        alignItems:'center',
        marginLeft:20,
        marginVertical:20,
        fontStyle:'bold'
    },
    image:
    {   
        width:50,
        height:30,
        marginHorizontal:20,
        marginVertical:20,
        marginLeft:70,
    },
    viewcenter:
    {
        backgroundColor:'white',
        marginHorizontal:20,
        marginVertical:20,
        borderRadius:30
    },
    viewregister:
    {
        justifyContent:'center',
        alignItems:'center',
        marginTop:20,
        marginBottom:20
    },
    textcenter:
    {
        color:'red',
        fontSize:15,
        marginLeft:20,
        marginTop:15
    },
    textinput:
    {   
        fontSize:15,
        borderBottomWidth:1,
        marginHorizontal:20,
        borderBottomColor:'red'
    },
    touch:
    {
        width:180,
        borderWidth:2,
        borderRadius:20,
        backgroundColor:'red',
        justifyContent:'center',
        alignItems:'center'
    },
    texttouch:
    {
        height:30,
        color:'white'
    },
    textend:
    {
        color:'black'
    },
    imagemethods:
    {
        width:30,
        height:30,
        marginLeft:20,
        marginTop:20
    }
})
export {StyleView}